# The URL the site will be built for
base_url = "https://jyn.dev"

description = "i write about code, and things that bring me joy, and sometimes other things too"

# used in feeds by default
title = "the website of jyn"

output_dir = "build"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# We don't use use `highlight_themes_css` because we have a custom theme (and textmate grammar is annoying and less flexible than CSS classes)
highlight_theme = "css"

[extra]
# Put all your custom variables here
email = "blog@jyn.dev"
linkedin_username = "jynelson"
github_username = "jyn514"